CREATE DATABASE  IF NOT EXISTS `shop`;

USE `shop`;

CREATE TABLE IF NOT EXISTS `goods`(
     `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     `name` CHAR(50) NOT NULL,
     `quantity` INT UNSIGNED NOT NULL,
     `price` DECIMAL(15,2) NOT NULL,
     `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
