Parameters:
  EventRuleName:
    Description: event rule default name
    Type: String
    Default: seven-cloudwatch-learn-event-rule-filter
  CustomMetricsNamespace:
    Description: custom metrics default namespace
    Type: String
    Default: seven-metrics-namespace
  CustomMetricName:
    Description: custom metrics default name
    Type: String
    Default: seven-filter-metric
Resources:
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Ref EventRuleName
      Description: 'ScheduledRule to trigger lambda regularly for CloudWatch learn session'
      ScheduleExpression: 'rate(1 minute)'
      State: 'ENABLED'
      Targets:
        - Arn:  !ImportValue LambdaFunctionArn
          Id: !Join ['-', [!ImportValue LambdaFunctionName,  'event-rule-filter'] ]
          Input: !Sub '{"from": "filter-event","info": "event rule trigger from filter"}'
  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue LambdaFunctionName
      Action: 'lambda:InvokeFunction'
      Principal: 'events.amazonaws.com'
      SourceArn: !GetAtt 'ScheduledRule.Arn'
  LogFilter:
    Type: AWS::Logs::MetricFilter
    Properties: 
      LogGroupName: !Join [ '', [ '/aws/lambda/', !ImportValue LambdaFunctionName ] ]
      FilterPattern: '"seven-lambda-filter request "'
      MetricTransformations:
        - MetricValue: 1
          DefaultValue: 0
          MetricNamespace: !Ref CustomMetricsNamespace
          MetricName: !Ref CustomMetricName
  FilterAlarmSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: seven-alarm-topic-filter
      Subscription:
        - Protocol: email
          Endpoint: 'lisheng.zi@thoughtworks.com'
  LambdaCustomMetricsFilterAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: seven-cloudwatch-learn-alarm-filter
      AlarmDescription: 'Alarm if lambda errors occur'
      Namespace: !Ref CustomMetricsNamespace
      MetricName: !Ref CustomMetricName
      Dimensions:
        - Name: FunctionName
          Value: !ImportValue LambdaFunctionName
      Statistic: Sum
      ComparisonOperator: GreaterThanThreshold
      Threshold: 10
      EvaluationPeriods: 2
      Period: 300
      TreatMissingData: breaching
      AlarmActions:
        - !Ref FilterAlarmSNSTopic
  