version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks: 
      - fontend-services
  html:
    image: nginx:alpine
    volumes: 
      - ./html/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/app
    networks: 
      - fontend-services
      - backend-services
  app:
    build:
      context: ./php
      dockerfile: Dockerfile-dev
    volumes:
      - ./php:/app
    networks: 
      - backend-services
  mysql:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks: 
      - backend-services
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
  redis:
    image: redis:5.0.10-alpine
    networks: 
      - backend-services

networks: 
  backend-services:
    driver: bridge
  fontend-services:
    driver: bridge

volumes:
  db-data:
