version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  html:
    build:
      context: ./html
      dockerfile: Dockerfile-dev
    volumes: 
    - ./php:/var/www/html
  app:
    build:
      context: ./php
      dockerfile: Dockerfile-dev
    volumes:
      - ./php:/app
  mysql:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=123456
